name: my_first_flutter_app
description: "My first flutter app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1
#packages
dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #state management
  get: ^4.6.5
  get_storage: ^2.1.1

  #utility packages:
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0

  # Firebase
  firebase_core: ^3.4.0
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  #image assets
  assets:
     - assets/logos/
     - assets/icons/
     - assets/images/
     - assets/Products/

  #Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
