// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5y_Sn-yrqscuVYd121NlMEPOs0120IE',
    appId: '1:249787863007:android:623bb5681bebc846563e6a',
    messagingSenderId: '249787863007',
    projectId: 'instax-449fd',
    storageBucket: 'instax-449fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtw--sHhdWpPLit_oF6sMPc1pMnFCy6JA',
    appId: '1:249787863007:ios:bf526ec41d4150fb563e6a',
    messagingSenderId: '249787863007',
    projectId: 'instax-449fd',
    storageBucket: 'instax-449fd.appspot.com',
    androidClientId: '249787863007-q079ut0jvd4m2mfkbq1ji5pk7d9t4hnf.apps.googleusercontent.com',
    iosClientId: '249787863007-uar9hcm3jjohbb8pvsu58d1436q28rch.apps.googleusercontent.com',
    iosBundleId: 'com.hassan.myFirstFlutterApp',
  );

}